'use client';
import {useEffect,useMemo,useState} from 'react';
type P={id:number,name:string,brand:string,cat:string,price:number,color:string,fit:string[]};
const ps:P[]=[
 {id:1,name:'NXR2 街頭全罩安全帽',brand:'SHOEI',cat:'安全帽',price:16800,color:'violet',fit:['全車種']},
 {id:2,name:'HI-SPEED 傳動套件',brand:'POLINI',cat:'傳動',price:6980,color:'blue',fit:['YAMAHA 勁戰六代 2024','YAMAHA FORCE 2.0 2023']},
 {id:3,name:'RS24 後避震器',brand:'MALOSSI',cat:'前後避震',price:12800,color:'red',fit:['SYM JET SL+ 2024','SYM DRG 2023']},
 {id:4,name:'浮動浪花碟盤 260mm',brand:'POLINI',cat:'碟盤',price:4200,color:'silver',fit:['YAMAHA 勁戰六代 2024']},
 {id:5,name:'競技陶瓷煞車皮',brand:'MALOSSI',cat:'煞車皮',price:1680,color:'yellow',fit:['SYM JET SL+ 2024','SYM MMBCU 2024']},
 {id:6,name:'AERO 短版燻黑風鏡',brand:'YEHDA',cat:'風鏡',price:2380,color:'smoke',fit:['YAMAHA FORCE 2.0 2023','SYM DRG 2023']}
];
const cats=['全部商品','風鏡','傳動','前後避震','碟盤','煞車皮','安全帽']; const nt=(n:number)=>`NT$ ${n.toLocaleString()}`;
export default function App(){const[page,setPage]=useState('home'),[cart,setCart]=useState<number[]>([]),[fav,setFav]=useState<number[]>([]),[cat,setCat]=useState('全部商品'),[maker,setMaker]=useState(''),[model,setModel]=useState(''),[year,setYear]=useState(''),[picked,setPicked]=useState(ps[0]),[step,setStep]=useState(1),[tab,setTab]=useState('數據總覽'),[toast,setToast]=useState('');
 useEffect(()=>{try{setCart(JSON.parse(localStorage.getItem('cart')||'[]'));setFav(JSON.parse(localStorage.getItem('fav')||'[]'))}catch{}},[]);useEffect(()=>{localStorage.setItem('cart',JSON.stringify(cart));localStorage.setItem('fav',JSON.stringify(fav))},[cart,fav]);
 const go=(x:string)=>{setPage(x);scrollTo({top:0,behavior:'smooth'})},add=(id:number)=>{setCart(x=>[...x,id]);setToast('已加入購物車');setTimeout(()=>setToast(''),1500)},heart=(id:number)=>setFav(x=>x.includes(id)?x.filter(i=>i!==id):[...x,id]),detail=(p:P)=>{setPicked(p);go('detail')};
 const filtered=useMemo(()=>ps.filter(p=>(cat==='全部商品'||p.cat===cat)&&(!maker||p.fit.some(x=>x.includes(maker))||p.fit[0]==='全車種')&&(!model||p.fit.some(x=>x.includes(model))||p.fit[0]==='全車種')&&(!year||p.fit.some(x=>x.includes(year))||p.fit[0]==='全車種')),[cat,maker,model,year]);const cp=cart.map(id=>ps.find(p=>p.id===id)!).filter(Boolean),total=cp.reduce((s,p)=>s+p.price,0);
 if(page==='admin')return <Admin tab={tab} setTab={setTab} back={()=>go('home')}/>;
 return <div><div className="ticker"><span>義大利性能部品・台灣專業選品</span><span>滿 NT$3,000 免運費</span><span>DEMO 展示站｜所有交易皆為模擬</span></div><header><button className="logo" onClick={()=>go('home')}><b>燁達</b><span>YEHDA MOTO<br/>PERFORMANCE</span></button><nav><button onClick={()=>go('products')}>所有商品</button><button onClick={()=>go('brands')}>品牌專區</button><button onClick={()=>{setCat('安全帽');go('products')}}>安全帽</button><button onClick={()=>document.querySelector('#fit')?.scrollIntoView()}>依車種找部品</button><button>改裝誌</button></nav><div className="tools"><button>⌕</button><button onClick={()=>go('favorites')}>♡<i>{fav.length}</i></button><button onClick={()=>go('cart')}>袋<i>{cart.length}</i></button><button className="adminBtn" onClick={()=>go('admin')}>後台展示 ↗</button></div></header><main>
 {page==='home'&&<><section className="hero"><div className="heroCopy"><p className="eyebrow">RIDE BEYOND LIMITS · 2026</p><h1>為街道而生<br/><em>為性能而戰</em></h1><p>從義大利競技血統，到日常騎乘的每個細節。<br/>嚴選真正值得你信賴的機車精品。</p><button className="primary" onClick={()=>go('products')}>探索所有部品　→</button><button className="ghost" onClick={()=>document.querySelector('#fit')?.scrollIntoView()}>依愛車精準選購</button></div><div className="bikeArt"><div className="slash"/><div className="machine"><b>YEHDA</b><span>RACING<br/>DIVISION</span></div><i className="wheel one"/><i className="wheel two"/><strong>01<small>STREET<br/>PERFORMANCE</small></strong></div></section>
 <section className="fit" id="fit"><div><p className="eyebrow purple">FIND YOUR PARTS</p><h2>選擇你的愛車</h2><p>只顯示真正適合你的改裝部品</p></div><div className="fitFields"><label>廠牌<select value={maker} onChange={e=>{setMaker(e.target.value);setModel('')}}><option value="">選擇廠牌</option><option>YAMAHA</option><option>SYM</option></select></label><label>車系 / 車款<select disabled={!maker} value={model} onChange={e=>setModel(e.target.value)}><option value="">選擇車款</option>{maker==='YAMAHA'?<><option>勁戰六代</option><option>FORCE 2.0</option></>:<><option>JET SL+</option><option>DRG</option><option>MMBCU</option></>}</select></label><label>年份<select disabled={!model} value={year} onChange={e=>setYear(e.target.value)}><option value="">選擇年份</option><option>2024</option><option>2023</option></select></label><button onClick={()=>go('products')}>搜尋適用部品 →</button></div></section>
 <section className="section"><Title kicker="CURATED FOR RIDERS" title="本週焦點選品" action={()=>go('products')}/><Grid items={ps.slice(0,4)} fav={fav} heart={heart} detail={detail} add={add}/></section><section className="categories"><Title kicker="SHOP BY CATEGORY" title="從你的下一項升級開始"/ ><div className="catGrid">{cats.slice(1).map((c,i)=><button key={c} onClick={()=>{setCat(c);go('products')}}><span>0{i+1}</span><b>{c}</b><small>PERFORMANCE PARTS</small><i>↗</i></button>)}</div></section><section className="brandStrip"><p className="eyebrow purple">OFFICIAL DISTRIBUTION</p><h2>義大利性能基因</h2><div><button onClick={()=>go('brands')}><b>POLINI</b><span>ITALIAN RACING PARTS<br/>SINCE 1945</span></button><button onClick={()=>go('brands')}><b>MALOSSI</b><span>RACING PERFORMANCE<br/>MADE IN ITALY</span></button></div></section></>}
 {page==='products'&&<section className="catalog"><PageTitle over="SHOP ALL" title={cat} sub={`${maker||'全車種'} ${model} ${year} ・ 共 ${filtered.length} 件符合商品`}/><div className="catalogBody"><aside><b>商品分類</b>{cats.map(c=><button className={cat===c?'active':''} onClick={()=>setCat(c)} key={c}>{c}<span>›</span></button>)}<hr/><b>品牌</b>{['POLINI','MALOSSI','SHOEI'].map(x=><label key={x}><input type="checkbox"/> {x}</label>)}</aside><div><div className="sort"><span>顯示 {filtered.length} 項商品</span><select><option>熱門排序</option><option>最新上架</option></select></div><Grid items={filtered} fav={fav} heart={heart} detail={detail} add={add}/></div></div></section>}
 {page==='detail'&&<section className="detail"><button className="back" onClick={()=>go('products')}>← 返回商品列表</button><Visual p={picked} big/><div className="detailInfo"><p className="eyebrow purple">{picked.brand} · {picked.cat}</p><h1>{picked.name}</h1><div className="stars">★★★★★ <span>4.9（28 則評價）</span></div><div className="price">{nt(picked.price)}</div><p>專為性能騎乘打造，兼顧街道實用與競技質感。台灣公司貨，提供專業適配諮詢。</p><hr/><label>規格<select><option>標準規格</option><option>黑 / 紫特仕版</option></select></label><div className="buy"><button className="primary" onClick={()=>add(picked.id)}>加入購物車</button><button onClick={()=>heart(picked.id)}>{fav.includes(picked.id)?'♥ 已收藏':'♡ 收藏'}</button></div><div className="fitNote"><b>✓ 適用車種</b>{picked.fit.map(x=><span key={x}>{x}</span>)}</div><ul><li>台灣公司貨／代理正品</li><li>7 日鑑賞期（未安裝商品）</li><li>專業安裝與適配諮詢</li></ul></div></section>}
 {page==='brands'&&<section className="brandPage"><PageTitle over="AUTHENTIC PERFORMANCE" title="品牌專區" sub="燁達嚴選全球頂級改裝品牌，把賽道科技帶進日常騎乘。"/>{['POLINI','MALOSSI'].map((b,i)=><article className={i?'redBrand':''} key={b}><div><span>MADE IN ITALY</span><h2>{b}</h2><p>{i?'源自義大利波隆那，以極致性能與大膽紅色基因聞名。':'創立於 1945 年，跨越三個世代的義大利傳動工藝。'}</p><button onClick={()=>go('products')}>探索 {b} 商品 →</button></div><b>{b[0]}</b></article>)}</section>}
 {page==='favorites'&&<section className="catalog single"><PageTitle over="YOUR PICKS" title="我的收藏" sub="你精選的性能升級清單"/>{fav.length?<Grid items={ps.filter(p=>fav.includes(p.id))} fav={fav} heart={heart} detail={detail} add={add}/>:<Empty text="還沒有收藏商品" go={()=>go('products')}/>}</section>}
 {page==='cart'&&<Cart items={cp} total={total} remove={i=>setCart(x=>x.filter((_,n)=>n!==i))} next={()=>{setStep(1);go('checkout')}} shop={()=>go('products')}/>} {page==='checkout'&&<Checkout step={step} setStep={setStep} items={cp} total={total} finish={()=>{setCart([]);go('home')}}/>}
 </main><footer><div><b>燁達</b><span>YEHDA MOTO PERFORMANCE</span><p>專業機車改裝・精品部品<br/>把每一次騎乘，升級成你要的樣子。</p></div><div><b>快速連結</b><a>所有商品</a><a>品牌專區</a><a>車種專區</a></div><div><b>顧客服務</b><a>配送說明</a><a>購物須知</a><a>退換貨政策</a></div><div><b>營業資訊</b><p>週一至週六 10:00–20:00<br/>客服專線 02-2345-6789<br/>新北市板橋區文化路 168 號</p></div><small>© 2026 燁達機車精品｜本網站為提案 Demo，所有內容與交易皆為模擬。</small></footer>{toast&&<div className="toast">✓ {toast}</div>}</div>}
function Title({kicker,title,action}:{kicker:string,title:string,action?:()=>void}){return <div className="title"><div><p className="eyebrow purple">{kicker}</p><h2>{title}</h2></div>{action&&<button onClick={action}>查看全部 1,000+ →</button>}</div>};function PageTitle({over,title,sub}:{over:string,title:string,sub:string}){return <div className="pageTitle"><p className="eyebrow purple">{over}</p><h1>{title}</h1><p>{sub}</p></div>}
function Visual({p,big}:{p:P,big?:boolean}){return <div className={`visual ${p.color} ${big?'big':''}`}><div className="part"><span>{p.brand}</span></div><small>{p.brand==='SHOEI'?'SHOEI 圖片位置 · DEMO':'DEMO PRODUCT'}</small></div>}
function Grid({items,fav,heart,detail,add}:{items:P[],fav:number[],heart:(i:number)=>void,detail:(p:P)=>void,add:(i:number)=>void}){return <div className="grid">{items.map(p=><article className="card" key={p.id}><button className="heart" onClick={()=>heart(p.id)}>{fav.includes(p.id)?'♥':'♡'}</button><button className="visualBtn" onClick={()=>detail(p)}><Visual p={p}/></button><div><small>{p.brand} · {p.cat}</small><button className="productName" onClick={()=>detail(p)}>{p.name}</button><p><b>{nt(p.price)}</b><button onClick={()=>add(p.id)}>＋</button></p></div></article>)}</div>}
function Empty({text,go}:{text:string,go:()=>void}){return <div className="empty"><span>◇</span><h2>{text}</h2><p>看到喜歡的商品，點擊愛心就能收藏。</p><button className="primary" onClick={go}>開始逛逛</button></div>}
function Cart({items,total,remove,next,shop}:{items:P[],total:number,remove:(i:number)=>void,next:()=>void,shop:()=>void}){return <section className="cartPage"><PageTitle over="YOUR BAG" title="購物車" sub={`${items.length} 件商品等待結帳`}/>{!items.length?<Empty text="購物車目前是空的" go={shop}/>:<div className="cartLayout"><div className="cartList">{items.map((p,i)=><article key={i}><Visual p={p}/><div><small>{p.brand} · {p.cat}</small><h3>{p.name}</h3><p>標準規格</p><button onClick={()=>remove(i)}>移除</button></div><div className="qty">−　1　＋</div><b>{nt(p.price)}</b></article>)}</div><Summary total={total}><button className="primary" onClick={next}>前往結帳 →</button></Summary></div>}</section>}
function Summary({total,children}:{total:number,children?:React.ReactNode}){return <aside className="summary"><h2>訂單摘要</h2><p><span>商品小計</span><b>{nt(total)}</b></p><p><span>運費</span><b>{total>=3000?'免運':'NT$ 120'}</b></p><hr/><p className="total"><span>總計</span><b>{nt(total+(total>=3000?0:120))}</b></p>{children}<small>🔒 安全結帳・本頁僅為 UI 模擬</small></aside>}
function Checkout({step,setStep,items,total,finish}:{step:number,setStep:(n:number)=>void,items:P[],total:number,finish:()=>void}){if(step===4)return <section className="done"><div>✓</div><p className="eyebrow purple">ORDER COMPLETE</p><h1>訂單模擬完成！</h1><p>訂單編號 <b>YD260828-0186</b></p><span>確認信已模擬寄送至 demo@yehda.tw<br/>此流程未產生真實訂單或扣款。</span><button className="primary" onClick={finish}>返回首頁</button></section>;return <section className="checkout"><div className="checkTop"><button onClick={()=>step>1&&setStep(step-1)}>← 返回</button><b>燁達 YEHDA</b><span>安全結帳 DEMO</span></div><div className="steps">{['配送資訊','配送方式','付款方式','完成'].map((x,i)=><div className={step>=i+1?'on':''} key={x}><i>{step>i+1?'✓':i+1}</i><span>{x}</span></div>)}</div><div className="checkLayout"><div className="form"><h2>{['配送資訊','選擇配送方式','選擇付款方式'][step-1]}</h2>{step===1&&<div className="formGrid"><label>收件人姓名<input defaultValue="王小明"/></label><label>手機號碼<input defaultValue="0912-345-678"/></label><label className="wide">電子信箱<input defaultValue="demo@yehda.tw"/></label><label>縣市<select><option>新北市</option></select></label><label>地區<select><option>板橋區</option></select></label><label className="wide">詳細地址<input defaultValue="文化路一段 168 號"/></label></div>}{step===2&&<Choices name="ship" rows={[['黑貓宅急便','1–2 個工作天 · NT$ 120'],['7-ELEVEN 超商取貨','2–4 個工作天 · NT$ 60'],['全家超商取貨','2–4 個工作天 · NT$ 60'],['中華郵政','2–3 個工作天 · NT$ 80']]}/>} {step===3&&<><Choices name="pay" rows={[['綠界科技｜信用卡','VISA · Mastercard · JCB（模擬）'],['超商取貨付款','取貨時支付商品款項'],['ATM 虛擬帳號','付款期限 3 天']]}/><div className="notice">ⓘ 此為 Demo，不會連線綠界、不會收集或處理真實卡號。</div></>}<button className="primary next" onClick={()=>setStep(step+1)}>{step===3?'確認送出模擬訂單':'繼續下一步'} →</button></div><Summary total={total||6980}/></div></section>}
function Choices({name,rows}:{name:string,rows:string[][]}){return <div className="choices">{rows.map((r,i)=><label key={r[0]}><input type="radio" name={name} defaultChecked={!i}/><b>{r[0]}</b><span>{r[1]}</span></label>)}</div>}
const tabs=['數據總覽','商品管理','分類管理','品牌管理','車種資料庫','適配管理','訂單管理','退貨管理','會員管理','首頁／內容管理','主要設定'];
function Admin({tab,setTab,back}:{tab:string,setTab:(s:string)=>void,back:()=>void}){return <div className="admin"><aside><div className="adminLogo"><b>燁達</b><span>STORE ADMIN</span></div><nav>{tabs.map((x,i)=><button className={tab===x?'active':''} onClick={()=>setTab(x)} key={x}><i>{['⌁','□','▦','◆','⌖','↔','▤','↩','♙','✦','⚙'][i]}</i>{x}{x==='訂單管理'&&<em>8</em>}</button>)}</nav><button className="store" onClick={back}>← 返回前台商城</button></aside><main><header><div><p>燁達機車精品 / {tab}</p><h1>{tab}</h1></div><div><button>⌕</button><button>♢<i>3</i></button><span>YD</span><b>管理員<small>admin@yehda.tw</small></b></div></header>{tab==='數據總覽'?<Dashboard/>:<AdminTable tab={tab}/>}</main></div>}
function Dashboard(){return <div className="dashboard"><div className="date"><span>最後更新：今天 23:48</span><button>近 30 天⌄</button><button className="adminPrimary">＋ 新增商品</button></div><div className="kpis">{[['本月營業額','NT$ 486,820','↑ 12.8%'],['本月訂單','186','↑ 8.4%'],['平均客單價','NT$ 2,617','↑ 3.1%'],['待處理訂單','8','需處理']].map((x,i)=><article key={x[0]}><span>{['＄','▤','↗','！'][i]}</span><small>{x[0]}</small><b>{x[1]}</b><em>{x[2]}</em></article>)}</div><div className="dashGrid"><section className="chart"><h2>營業額趨勢 <small>近 7 日</small></h2><div>{[34,48,40,64,58,82,72].map((n,i)=><i key={i} style={{height:n+'%'}}/>)}</div><p><span>08/22</span><span>08/23</span><span>08/24</span><span>08/25</span><span>08/26</span><span>08/27</span><span>今天</span></p></section><section className="orders"><h2>最新訂單 <button>查看全部 →</button></h2>{[['#YD0186','王小明','NT$ 6,980','待出貨'],['#YD0185','林柏宇','NT$ 12,800','已付款'],['#YD0184','陳冠廷','NT$ 4,060','處理中'],['#YD0183','張家豪','NT$ 16,800','已完成']].map(x=><p key={x[0]}><b>{x[0]}</b><span>{x[1]}</span><strong>{x[2]}</strong><em>{x[3]}</em></p>)}</section></div><div className="dashGrid lower"><section className="stock"><h2>低庫存提醒 <button>管理庫存 →</button></h2>{ps.slice(0,4).map((p,i)=><p key={p.id}><i className={p.color}/><b>{p.name}<small>{p.brand} · SKU YD-00{p.id}</small></b><em>剩 {i+2} 件</em></p>)}</section><section className="quick"><h2>快速操作</h2><div>{['新增商品','建立訂單','新增車種','更新首頁','匯出報表','網站設定'].map(x=><button key={x}>＋<span>{x}</span></button>)}</div></section></div></div>}
function AdminTable({tab}:{tab:string}){return <div className="adminTable"><div className="listTools"><div><button className="active">全部</button><button>上架中</button><button>草稿</button></div><div><input placeholder={`搜尋${tab}…`}/><button>篩選⌄</button><button className="adminPrimary">＋ 新增項目</button></div></div><section><table><thead><tr><th>□</th><th>項目名稱</th><th>狀態</th><th>售價／日期</th><th>庫存／資料</th><th>操作</th></tr></thead><tbody>{ps.map((p,i)=><tr key={p.id}><td>□</td><td><i className={`tableImg ${p.color}`}>{p.brand[0]}</i><b>{tab==='商品管理'?p.name:`${tab.replace('管理','')}項目 ${i+1}`}<small>{p.brand} · YD-00{p.id}</small></b></td><td><span className="status">● 上架中</span></td><td>{nt(p.price)}</td><td>{12-i} 件</td><td><button>編輯</button><button>•••</button></td></tr>)}</tbody></table></section><p className="pagination">顯示 1–6，共 186 筆　　‹　<b>1</b>　2　3　…　31　›</p></div>}
